name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - run: sbt -v "+ run"
